### PR TITLE
Add blobs

### PR DESCRIPTION
**Pull request by andreufont**
I just noticed that the PR was to merge with master, while what we want is to merge with cmb_compressed. 

Unless you think that one is also ready to be merged in master...

Just in case, I'm opening a new PR, to merge with cmb_compressed.

-- from old PR ---

I merged the changes from cmb_compressed, and the notebooks are running well. Take a look at test_blobs.ipynb under notebooks/development.

I wouldn't merge yet, since I need to implement the blobs for the specific case of running with the same background (it should be easy).

@Chris-Pedersen - if you wanted you could start playing with it, though. It would be nice to add some extra plotting functionality, to add derived parameters from the blobs in the corner plots.

### CODE REVIEW

**Comment by Chris-Pedersen** [comment]
Hi @andreufont thanks for the new PR - let me add a bit of plotting functionality and test the backend before we merge just for completeness, I'll get round to this before Monday!

**Comment by andreufont** [comment]
Sounds great!

**Comment by Chris-Pedersen** [comment]
This is all working now on my desktop, I went to run some chains on Hypatia overnight but got the following error when running `setup.py`:

```
  File "build/bdist.linux-x86_64/egg/lace/likelihood/full_theory.py", line 232
    return np.nan,*([np.nan]*(Nblob-1))
                  ^
SyntaxError: invalid syntax
```

Basically syntax errors for all of the asterisk operations. I guess this is a Python version issue - I'm on 3.6.4 on Hypatia and 3.8.3 on my deskop where I've been developing and debugging this branch. Can you confirm that you're also on something later than 3.6.4? I guess I'll have to update my Hypatia Python version or try and figure out some virtual environment asap if this is the case!

**Comment by Chris-Pedersen** [comment]
Ok I am actually not getting this error on Kathleen, which is also Python 3.6 so there is probably something else going on on Hypatia. I've emailed Edd so hopefully he will know what's going on.

**Comment by andreufont** [comment]
I'm using python 3.7, but Google is telling me that any change related to this should be related to python-2 vs python-3... Does this happen both in a notebook and in a terminal?

**Comment by Chris-Pedersen** [comment]
It happens at the point of running setup.py. I need to find a simple ~5 line example that breaks on Hypatia. More googling indicates that a lot of these * operations were introduced in 3.5, so anything over that should be fine. It works on Kathleen which is also Python 3.6 so I think there's a specific problem with the Python version on Hypatia.

**Comment by andreufont** [comment]
Argh, this is annoying... let's hope Edd can help!

How about asking in the Slack channel, or email list? 

Others might have found this issue

**Comment by Chris-Pedersen** [comment]
Working on Hypatia so merging!

**Pull request merged**
