### PR TITLE
Fix get_f_of_z and use_camb_fz=True by default

### PR DESCRIPTION
**Pull request by andreufont**
@Chris-Pedersen - I decided to make a smaller PR that we can merge first to cmb_compressed, while I work on other parts (add_blobs). 

This just moves to using the CAMB function to compute f(z) instead of the numerical derivative.

I will add a notebook to show that the two functions give very similar results.

### CODE REVIEW

**Comment by andreufont** [comment]
@Chris-Pedersen - take a look at the new notebook test_f_of_z, that shows that the changes do not change the values of f_star

**Comment by Chris-Pedersen** [comment]
Can run the notebook fine and it looks good - adding a timer calling `parameterize_cosmology_kms` goes from taking ~0.5s to ~0.02. One thing I'm a bit confused about though is that I don't see any difference in the time it takes to make a likelihood evalation, even when using a `full_theory` object with `use_compresion=True`. I was expecting that this would take a lot longer in the previous setup, as we would have to be calling a new `get_camb_results()` for the extra redshifts to compute f numerically, but for some reason I don't see this on the other branch.

Either way I'm happy to merge this, although I would like to understand why this isn't happening tomorrow.

**Comment by andreufont** [comment]
@Chris-Pedersen - do you have an example of running full_theory with use_compression? I could time that and figure out why.

**Comment by Chris-Pedersen** [comment]
You just need to add a use_compression=True flag when constructing the likelihood object in sampler_template. I added a timer and compared the two branches and saw no difference, which was suprising

**Pull request merged**
