### PR TITLE
Naim covariance

### PR DESCRIPTION
**Pull request by andreufont**
I have added two simple objects to represent P1D measurements from Naim: one from his DESI-lite mocks (Karacayli et al. 2020) and one from the high-resolution mocks he is running right now.

For now I have only added a diagonal covariance matrix to get something running. In the long term we will want to use a full covariance matrix, that takes into account correlations between redshift bins, but this would require a fair amount of work.

### CODE REVIEW

**Comment by andreufont** [comment]
I have also updated one of the old notebooks comparing P1D data, and added plots comparing these new data sets.

**Comment by andreufont** [comment]
Finally, I've modified data_MPGADGET to be able to use DESI covariances for the mocks. 

I've added a new notebook to compare DESI vs eBOSS forecasts.

**Comment by andreufont** [comment]
Hi @Chris-Pedersen - should we merge this branch?

**Comment by Chris-Pedersen** [comment]
Tested this is working on Hypatia, so merging!

**Pull request merged**
