### PR TITLE
Speed v2

### PR DESCRIPTION
**Pull request by andreufont**
@Chris-Pedersen , this is basically the same PR than before, but without the controversial use of fiducial cosmo in the recons_cosmo object. 

I have also changed camb_model_fid to true_camb_model in the full_theory object, but I have not changed the way it is used.

I added the notebook, and the speeds look very good, so I think this one should be safe to merge.

### CODE REVIEW

**Comment by andreufont** [comment]
@Chris-Pedersen - two small changes needed:
- we were using the old name (camb_model_fid) in a couple of places.
- minor speed up when computing recons_cosmo object (we already have camb_results, pass it to linear_power)

**Comment by andreufont** [comment]
@Chris-Pedersen - I ran all 3 samplers, and it seems to be fine. Happy to merge!

**Review by Chris-Pedersen — APPROVED** [review]
Looks good! Happy to merge too

**Comment by andreufont** [comment]
@Chris-Pedersen - Pinging this conversation, relevant to ongoing work that I'd like to discuss next week.

**Pull request merged**
